### PR TITLE
Fix Schwab parsing

### LINKED ISSUE #451: "Totals" line missing from Schwab transactions csv export
Not sure if Schwab have updated their format, but I didn't get a "Transactions Total" line at the end of my exported csv file.

pasting the last line from the example.csv into my export got me past this error.

### LINKED ISSUE #457: Schwab equity award transactions history export csv is updated
I am receiving the following error when running the command:
```
$ cgt-calc --year 2022 --schwab XXXXX611_Transactions_20240104-182027.csv --schwab-award EquityAwardsCenter_Transactions_20240104182317.csv 
Traceback (most recent call last):
  File "/home/rahul/.local/bin/cgt-calc", line 8, in <module>
    sys.exit(init())
  File "/home/rahul/.local/pipx/venvs/cgt-calc/lib/python3.9/site-packages/cgt_calc/main.py", line 713, in init
    sys.exit(main())
  File "/home/rahul/.local/pipx/venvs/cgt-calc/lib/python3.9/site-packages/cgt_calc/main.py", line 672, in main
    broker_transactions = read_broker_transactions(
  File "/home/rahul/.local/pipx/venvs/cgt-calc/lib/python3.9/site-packages/cgt_calc/parsers/__init__.py", line 57, in read_broker_transactions
    transactions += read_schwab_transactions(
  File "/home/rahul/.local/pipx/venvs/cgt-calc/lib/python3.9/site-packages/cgt_calc/parsers/schwab.py", line 178, in read_schwab_transactions
    awards_prices = _read_schwab_awards(schwab_award_transactions_file)
  File "/home/rahul/.local/pipx/venvs/cgt-calc/lib/python3.9/site-packages/cgt_calc/parsers/schwab.py", line 264, in _read_schwab_awards
    raise UnexpectedColumnCountError(
cgt_calc.exceptions.UnexpectedColumnCountError: While parsing EquityAwardsCenter_Transactions_20240104182317.csv, The following row doesn't have 8 columns:
...
```
I believe the format of csv export for Schwab Equity Awards Transaction history has changed.

### LINKED ISSUE #464: Schwab Transaction History format has changed (price is now before qty)
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/cgt_calc/parsers/schwab.py", line 194, in read_schwab_transactions
    raise ParsingError(
cgt_calc.exceptions.ParsingError: While parsing schwab-transaction-history.csv, First line of Schwab transactions file must be something like 'Transactions for account ...'

Looking into the code and the file, it seems that it used to expected price column to be after quantity but this seems to have changed in the latest CSV export format

### PR DESCRIPTION
**Pull request by amaramrahul**
Updated parser logic for Schwab

Fixes #451 
Fixes #457 
Fixes #464

### CODE REVIEW

**Comment by vmartinv** [comment]
Can you try again? I downloaded my transactions and it looks like Quantity and Price columns are swapped.

**Comment by amaramrahul** [comment]
> Can you try again? I downloaded my transactions and it looks like Quantity and Price columns are swapped.

Ah yes. You are right. Not sure if this is temporary or permanent. I guess the proper fix would be to determine the column purpose based on the header.

**Comment by vmartinv** [comment]
> Ah yes. You are right. Not sure if this is temporary or permanent. I guess the proper fix would be to determine the column purpose based on the header.

I agree. If you add this I can test it on my statement. You can do something like this:
```
    for upper_row, lower_row in zip(lines[::2], lines[1::2]):
        # in this format each row is split into two rows, so we combine them safely below
        row = []
        for upper_col, lower_col in zip(upper_row, lower_row):
            assert upper_col == "" or lower_col == ""
            row.append(upper_col + lower_col)

        if len(row) != len(header):
            raise UnexpectedColumnCountError(
                row, len(header), schwab_award_transactions_file or ""
            )

        row = dict(zip(header, row))
        date_str = row["Date"]
```

**Comment by amaramrahul** [comment]
@vmartinv I have made the changes and tested using Individual Transaction History and Equity Awad Transaction History file. Please test and if you have permission, merge the changes.

**Comment by vmartinv** [comment]
I think it looks good but can you also add a validation to make sure the columns are as expected? Something like this:
```
    expected_header = {
        "Date",
        "Action",
        "Symbol",
        "Description",
        "Quantity",
        "FeesAndCommissions",
        "DisbursementElection",
        "Amount",
        "AwardDate",
        "AwardId",
        "FairMarketValuePrice",
        "SalePrice",
        "SharesSoldWithheldForTaxes",
        "NetSharesDeposited",
        "Taxes",
    }
    header = lines[0]
    if set(header) != expected_header:
        raise ParsingError(
            schwab_award_transactions_file,
            f"Missing or unknown columns in awards file: {expected_header.symmetric_difference(header)}",
        )
```

**Comment by amaramrahul** [comment]
I did not do this because I didn't want the script to break if an additional column is added that we do not use. However, I also see the reason why we need to check for headers. So, I have taken an intermediate ground and updated the code to ensure that the headers that we are using are present in the transactions file. We do not care if there are additional headers in the transactions file that we are not using.

**Comment by vmartinv** [comment]
I can confirm this PR works as expected, it parsed my latest Schwab files and generated the report correctly. Can you confirm @KapJI ?

**Comment by KapJI** [comment]
Looks good, thank you!

And thanks @vmartinv for help with reviewing this.

**Pull request merged**
